Add Eaternity
pogopaule/awesome-sustainability-jobs pull request #32
Opened 2023-08-18 14:27 UTC by mklarmann

- [x ] I read [CONTRIBUTING.md](https://github.com/pogopaule/awesome-sustainability-jobs/blob/main/CONTRIBUTING.md)  
- [x ] I didn't change README.md (but instead src/data.yaml or src/template.md)

2023-09-09 12:56 UTC, pogopaule requested changes
Thank you for your contribution! There is just this minor change you need to make.

2023-09-09 12:56 UTC, pogopaule commented on src/data.yaml
> +    field: Carbon Analysis of Foods
There is just this general category

```suggestion
    field: Carbon Analysis, Capture and Offsetting
```

2023-09-11 19:36 UTC, mklarmann commented
ok

2023-09-11 19:36 UTC, closed without merging

2023-09-12 11:15 UTC, pogopaule commented
Did you really want to close the PR? It looks good to me.